# GET http://localhost:2025/api/program

# GET http://localhost:2025/api/program/rating

# GET http://localhost:2025/api/program/sort/producer_id

# GET http://localhost:2025/api/program/search?format=live-action&program_rating=PG

# GET http://localhost:2025/api/program/program_info

# GET http://localhost:2025/api/program/program_rating

# GET http://localhost:2025/api/producer 

# GET http://localhost:2025/api/producer/producer/5

#  GET http://localhost:2025/api/producer/search?producer=disney&title=

# GET http://localhost:2025/api/producer/producer/producer/3

