-- This file was use to input all of the information in the database
-- PRODUCTION
INSERT INTO producer (producer)
VALUES
('the walt disney company'),
('rankin/bass productions'),
('universal pictures'),
('mgm'),
('mendelson/melendez productions'),
('hughes entertainment'),
('cube vision'),
('netflix'),
('amazon studios'),
('apple tv');

-- DIRECTOR
INSERT INTO director (first_name, last_name)
VALUES
('david', 'talbert'),
('yarrow', 'cheney'),
('scott', 'mosier'),
('ron', 'howard'),
('chuck', 'jones'),
('ben', 'washam'),
('reginald', 'hudlin'),
('bill', 'melendez'),
('arthur', 'ranking jr'),
('jules', 'bass'),
('larry', 'roemer'),
('jeremiah', 'chechik'),
('kevin', 'deters'),
('stevie', 'wermers-skelton'),
('sergio', 'pablos'),
('carlos martinez', 'lopez'),
('alex', 'mann'),
('bradley', 'raymond'),
('jun', 'falkenstein'),
('bill', 'speers'),
('toby', 'shelton'),
('matthew', "o'callaghan"),
('burny', 'mattinson'),
('marcus', 'raboy'),
('sean', 'anders'),
('john', 'harvatine iv'),
('jamie', 'badminton'),
('rufus', 'blacklock');

-- STREAMING PLATFORM
INSERT INTO streaming_platform (streaming_platform)
VALUES
('apple tv'),
('pluto tv'),
('amazon prime'),
('disney plus'),
('freevee'),
('hbo max'),
('hulu'),
('netflix'),
('paramount plus'),
('peacock'),
('sling tv'),
('roku'),
('starz'),
('tubi'),
('youtube');

-- ACTOR
INSERT INTO actor (first_name, last_name)
VALUES
('danny', 'glover', 'danny_glover.jpeg'),
('gabrielle', 'union', 'gabrielle_union.jpeg'),
("mo'nique", '', 'mo_nique.jpeg'),
('kimberly', 'elise', 'kimberly_elise.jpeg'),
('romany', 'malco', 'romany_malco.jpeg'),
('benedict','cumberbatch', 'benedict_cumberbatch.jpeg'),
('rashida', 'jones', 'rashida_jones.jpeg'),
('kenan', 'thompson', 'kenan_thompson.jpeg'),
('cameron',	'seely', 'cameron_seely.jpeg'),
('angela', 'lansbury', 'angela_lansbury.jpeg'),
('jim', 'carrey', 'jim_carrey.jpeg'),
('taylor', 'momsen', 'taylor_momsen.jpeg'),
('jeffrey',	'tambor', 'jeffrey_tambor.jpeg'),
('christine', 'baranski', 'christine_baranski.jpeg'),
('bill', 'irwin', 'bill_irwin.jpeg'),
('boris', 'karloff', 'boris_karloff.jpeg'),
('june', 'foray', 'june_foray.jpeg'),
('dal', 'mckennon', 'dal_mckennon.jpeg'),
('thurl', 'ravenscroft', 'thurl_ravenscroft.jpeg'),
('forest', 'whitaker', 'forest_whitaker.jpeg'),
('keegan-michael', 'key', 'keegan_michael_key.jpeg'),
('madalen', 'mills', 'madalen_mills.jpeg'),
('anika', 'rose', 'anika_rose.jpeg'),
('phylicia', 'rashad', 'phylicia_rashad.jpeg'),
('eddie', 'murphy',	'eddie_murphy.jpeg'),
('tracee ellis', 'ross', 'tracee_ellis_ross.jpeg'),
('jillian', 'bell', 'jillian_bell.jpeg'),
('nick', 'offerman', 'nick_offerman.jpeg'),
('david alan', 'grier', 'david_alan_grier.jpeg'),
('peter', 'robbins', 'peter_robbins.jpeg'),
('christopher', 'shea', 'christopher_shea.jpeg'),
('tracy', 'stratford', 'tracy_stratford.jpeg'),
('cathy', 'steinberg', 'cathy_steinber.jpeg'),
('bill', 'melendez', 'bill_melendez.jpeg'),
('shirley', 'booth', 'shirely_booth.jpeg'),
('mickey', 'rooney', 'mickey_rooney.jpeg'),
('dick', 'shawn', 'dick_shawn.jpeg'),
('george s.', 'irving', 'george_s_irving.jpeg'),
('bob', 'mcfadden', 'bob_mcfadden.jpeg'),
('fred', 'astaire',	'fred_astaire.jpeg'),
('keenan', 'wynn', 'keenan_wynn.jpeg'),
('paul', 'frees', 'paul_frees.jpeg'),
('robie', 'lester', 'robie_lester.jpeg'),
('burl', 'ives', 'burl_ives.jpeg'),
('billie mae', 'richards', 'billie_mae_richards.jpeg'),
('larry d.', 'mann', 'larry_d_mann.jpeg'),
('paul', 'soles', 'paul_soles.jpeg'),
('stan', 'francis', 'stan_francis.jpeg'),
('chevy', 'chase', 'chevy_chase.jpeg'),
('beverly', "d'angelo",	'beverly_d_angelo.jpeg'),
('randy', 'quaid', 'randy_quaid.jpeg'),
('juliette', 'lewis', 'juliette_lewis.jpeg'),
('johnny', 'galecki', 'johnny_galecki.jpeg'),
('dave', 'foley', 'dave_foley.jpeg'),
('derek', 'richardson', 'derek_richardson.jpeg'),
('sarah', 'chalke', 'sarah_chalke.jpeg'),
('william morgan', 'sheppard', 'william_morgan_sheppard.jpeg'),
('mason vale', 'cotton', 'mason_vale_cotton.jpeg'),
('rob', 'riggle', 'rob_riggle.jpeg'),
('chris', 'parnell', 'chris_parnell.jpeg'),
('jason', 'schwartzman', 'jason_schwartzman.jpeg'),
('jonathan kimble', 'simmons', 'jonathan_kimble_simmons.jpeg'),
('norm', 'macdonald', 'norm_macdonald.jpeg'),
('joan', 'cusack', 'joan_cusack.jpeg'),
('wayne', 'allwine', 'wayne_allwine.jpeg'),
('russi', 'taylor', 'russie_taylor.jpeg'),
('tony', 'anselmo', 'tony_anselmo.jpeg'),
('bill', 'farmer', 'bill_farmer.jpeg'),
('alan', 'young', 'alan_young.jpeg'),
('tress', 'macneille', 'tress_macneille.jpeg'),
('clarence', 'nash', 'clarence_nash.jpeg'),
('hal', 'smith', 'hal_smith.jpeg'),
('will', 'ryan', 'will_ryan.jpeg'),
('ice', 'cube', 'ice_cube.jpeg'),
('mike', 'epps', 'mike_epps.jpeg'),
('john', 'witherspoon',	'john_witherspoon.jpeg'),
('don', 'curry', 'don_curry.jpeg'),
('terry', 'crews', 'terry_crews.jpeg'),
('will', 'ferrell', 'will_ferrell.jpeg'),
('ryan', 'reynolds', 'ryan_reynolds.jpeg'),
('octavia', 'spencer', 'octavia_spencer.jpeg'),
('sunita', 'mani', 'sunita_mani.jpeg'),
('patrick',	'page', 'patrick_page.jpeg'),
('kaitlyn', 'robrock', 'kaitlyn_robrock.jpeg'),
('debra', 'wilson', 'debra_wilson.jpeg'),
('bret', 'iwan', 'bret_iwan.jpeg'),
('camryn', 'grimes', 'camryn_grimes.jpeg'),
('brock', 'powell', 'brock_powell.jpeg'),
('laurence', 'fishburne', 'laurence_fishburne.jpeg'),
('regina', 'king', 'regina_king.jpeg'),
('angela', 'bassett', 'angela_bassett.jpeg'),
('donielle t.', 'hansley jr.', 'donielle_t_hansley_jr.jpeg'),
('jamie-lynn', 'sigler', 'jamie_lynn_sigler.jpeg');


-- PROGRAM
INSERT INTO program (program_id, title, yr_released, runtime, producer_id, format, program_rating, rating, img_url, description)
VALUES
(1, 'almost christmas', 2016, '01:52:00', 3, 'live-action', 'PG-13', 6.2, 'almost christmas.jpeg', 'A recently widowed patriarch struggles to keep his eccentric family from falling apart during their first holiday without his wife.'),
(2, 'the grinch', 2018, '01:30:00', 3, 'animation', 'PG', 6.4, 'the grinch.jpeg', 'A grumpy, isolated Grinch plots to steal Christmas from the joyful Whos of Whoville until an unexpected act of kindness changes his heart.'),
(3, 'how the grinch stole christmas', 2001, '01:45:00', 3, 'live-action', 'PG', 6.4, 'how the grinch stole christmas.jpeg', 'The live-action tale of the Grinch whose childhood pain fuels his plan to ruin Christmas until he discovers the true meaning of the holiday.'),
(4, 'how the grinch stole christmas!', 1966, '00:26:00', 4, 'animation', 'NR', 8.0, 'how the grinch stole christmas!.jpeg', 'The classic animated special where the Grinch discovers that Christmas means more than gifts and decorations.'),
(5, 'jingle jangle: a christmas journey', 2020, '02:02:00', 8, 'live-action', 'PG', 6.4, 'jingle jangle.jpeg', 'A forgotten toymaker finds renewed hope when his inventive granddaughter helps reignite his creative spirit.'),
(6,	'candy cane lane', 2023, '02:00:00', 9, 'live-action', 'PG', 5.6, 'candy cane lane.jpeg', 'A dad desperate to win a neighborhood decoration contest accidentally unleashes magical chaos that threatens Christmas.'),
(7, 'a charlie brown christmas', 1965, '00:30:00', 5, 'animation', 'G', 8.3, 'a charlie brown christmas.jpeg', 'Charlie Brown searches for the real meaning of Christmas amid commercialism and finds hope through friendship and a small tree.'),
(8,	'the year without a santa claus', 1974, '01:00:00', 2, 'stop-motion', 'TV-G', 7.7, 'the year without a santa clause.jpeg', 'When Santa considers canceling Christmas due to illness, two elves embark on a mission to restore his faith in holiday spirit.'),
(9, "santa claus is comin' to town!", 1970, '00:51:00', 2,	'stop-motion', 'NR', 7.7, "santa claus is comin' to town.jpeg", 'This stop-motion origin story shows how Kris Kringle became Santa Claus despite obstacles from the winter wizard and the Burgermeister.'),
(10, 'rudolph the red nose reindeer', 1964, '00:55:00', 2, 'stop-motion', 'G', 8.0, 'rudolph the red nose reindeer.jpeg', 'Rudolph and his glowing nose prove their worth on a journey of acceptance, friendship, and saving Christmas.'),
(11, "national lampoon's christmas vacation", 1989, '01:37:00', 6, 'live-action', 'PG-13', 7.5, "national lampoon's christmas vacation.jpeg", "Clark Griswold's dream of a perfect family Christmas spirals into hilarious chaos and holiday mishaps."),
(12, 'prep & landing', 2009, '00:22:00', 1, 'animation', 'TV-G', 7.5, 'prep & landing.jpeg', "Two elite elf operatives ensure homes are ready for Santa's arrival until a risky mission tests their partnership."),
(13, 'prep & landing: naughty vs nice', 2011, '00:22:00', 1, 'animation', 'G', 7.3, 'prep & landing_naughty vs nice.jpeg', 'Tech-savvy elves race to stop a Christmas-threatening data breach while repairing their own sibling rivalry.'),
(14, 'klaus', 2019, '01:37:00',	8, 'animation', 'PG', 8.2, 'klaus.jpeg', 'A selfish postman befriends a reclusive toymaker and together they unintentionally spark the legend of Santa in a feuding town.'),
(15, "mickey's once upon a christmas", 1999, '01:10:00', 1, 'animation', 'G', 7.0, "mickey's once upon a christmas.jpeg", 'Mickey, Minnie, Donald, and Goofy star in three heartfelt holiday stories about love, gratitude, and giving.'),
(16, "mickey's twice upon a christmas",	2004, '01:08:00', 1, 'animation', 'G', 6.4, "mickey's twice upon a christmas.jpeg",	'A collection of festive animated shorts showing Mickey and friends learning lessons about kindness and holiday cheer.'),
(17,	"mickey's christmas carol", 1983, '00:26:00', 1, 'animation', 'G', 8.0, "mickey's christmas carol.jpeg", 'Disney characters reenact the classic *A Christmas Carol* with Scrooge McDuck as the miserly Ebenezer.'),
(18, 'friday after next', 2002, '01:28:00',	7, 'live-action', 'R', 5.8, 'friday after next.jpeg', 'Craig and Day-Day take security jobs after a Christmas Eve robbery leads to new holiday madness.'),
(19, 'spirited', 2022, '02:07:00', 10, 'live-action', 'PG-13', 6.6, 'spirited.jpeg', "A retelling of *A Christmas Carol* where a cynical modern man challenges the ghosts' annual redemption mission."),
(20, "mickey's christmas tales: starstruck", 2023, '00:03:00', 1, 'stop-motion', 'TV-G', 6.1, "mickey's christmas tales.jpeg", 'Mickey and friends embark on a charming adventure as they follow a mysterious Christmas star that leads to an unexpected holiday surprise.'),
(21, "mickey's christams tales: how to build a snowman", 2023, '00:02:10', 1, 'stop-motion', 'TV-G', 6.2, "mickey's christmas tales.jpeg", 'Mickey demonstrates how to build the perfect snowman, turning a simple winter activity into a cheerful lesson filled with seasonal fun.'),
(22, "mickey's christmas tales: holiday hideaway", 2023, '00:02:10', 1, 'stop-motion', 'TV-G', 6.5, "mickey's christmas tales.jpeg", 'The gang searches for an ideal holiday hideout, creating a warm, lighthearted story about finding comfort and togetherness.'),
(23, "mickey's christams tales: slip n' sleigh", 2023, '00:02:10', 1, 'stop-motion', 'TV-G', 5.4, "mickey's christmas tales.jpeg", 'Mickey and his friends experience a comedic sleigh mishap that highlights the playful unpredictability of holiday traditions.'),
(24, "mickey's christmas tales: up all eve", 2023, '00:02:10', 1, 'stop-motion', 'TV-G', 6.4, "mickey's christmas tales.jpeg", 'Mickey and the crew attempt to stay awake to welcome Christmas morning, resulting in a charming tale of anticipation and holiday excitement.'),
(25, 'the snowy day', 2016, '00:39:00', 9, 'animation', 'TV-G', 7.4, 'the snowy day.jpeg', 'Peter explores his snow-covered neighborhood with curiosity and Christmas wonder.');

-- PROGRAM_TO_ACTOR
INSERT INTO program_to_actor(program_id, actor_id)
VALUES
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5),
(2, 6), (2, 7), (2, 8), (2, 9), (2, 10),
(3, 11), (3, 12), (3, 13), (3, 14), (3, 15),
(4, 16), (4, 17), (4, 18), (4, 19),
(5, 20), (5, 21), (5, 22), (5, 23), (5, 24), 
(6, 25), (6, 26), (6, 27), (6, 28), (6, 29), 
(7, 30), (7, 31), (7, 32), (7, 33), (7, 34),
(8, 35), (8, 36), (8, 37), (8, 38), (8, 39),
(9, 36), (9, 40), (9, 41), (9, 42), (9, 43),
(10, 44), (10, 45), (10, 46), (10, 47), (10, 48),
(11, 49), (11, 50), (11, 51), (11, 52), (11, 53),
(12, 54), (12, 55), (12, 56), (12, 57), (12, 58),
(13, 54), (13, 55), (13, 56), (13, 59), (13, 60),
(14, 7), (14, 61), (14, 62), (14, 63), (14, 64), 
(15, 65), (15, 66), (15, 67), (15, 68), (15, 69), 
(16, 65),  (16, 66), (16, 67), (16, 68), (16, 70),
(17, 65), (17, 69), (17, 71), (17, 72), (17, 73),
(18, 74), (18, 75), (18, 76), (18, 77), (18, 78),
(19, 79), (19, 80), (19, 81), (19, 82), (19, 83),
(20, 67), (20, 68), (20, 84), (20, 85), (20, 86),
(21, 67), (21, 68), (21, 84), (21, 85), (21, 86),
(22, 67), (22, 68), (22, 84), (22, 85), (22, 86),
(23, 67), (23, 84), (23, 86), (23, 87), (23, 88),
(24, 67), (24, 68), (24, 84), (24, 86), (24, 88),
(25, 89), (25, 90), (25, 91), (25, 92), (25, 93);

-- PROGRAM_TO_DIRECTOR
INSERT INTO program_to_director
(program_id, director_id)
VALUES
(1, 1), (2, 2), (2, 3), (3, 4), (4, 5), 
(4, 6), (5, 1), (6, 7), (7, 8), (8, 9),(8, 10), 
(9, 9), (9, 10), (10, 11), (11, 12), (12, 13), 
(12, 14), (13, 13), (13, 14), (14, 15), (14, 16), 
(15, 17), (15, 18), (15, 19), (15, 20), (15, 21), 
(16, 22), (17, 23), (18, 24), (19, 25), (20, 26), 
(21, 26), (22, 26), (23, 26), (24, 26),(25, 27), (25, 28);

-- PROGRAM_TO_STREAMING
INSERT INTO program_to_streaming
(program_id, streaming_platform_id)
VALUES
(1, 10), (1, 6), (2, 10), (3, 10), (3, 3),
(3, 7), (4, 10), (4, 6), (4, 7), (5, 8),
(6, 3), (7, 1), (8, 6), (9, 6), (10, 6), (11, 6),
(12, 4), (13, 4), (14, 8), (15, 4), (16, 4),
(17, 4), (18, 6), (18, 7), (19, 1), (20, 4),
(21, 4), (22, 4), (23, 4), (24, 4), (25, 3);